name: flowerdecorations
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #1-Used for device screens sizes
  flutter_screenutil: ^5.3.1

  #2-Used for decoration
  flutter_spinkit: ^5.1.0

  #3-Used for Importing SVG Image
  flutter_svg: ^1.0.3

  #4-Used for Form Validation
  form_field_validator: ^1.1.0

  #5-Used for building QR Code
  barcode_widget: ^2.0.1

  #6-Used for user Authorization
  firebase_auth: ^3.3.11

  #7-Used for accessing Firebase cloud_firestore to store details
  cloud_firestore: ^3.1.10

  #8-Used for implementing Firebase functions
  firebase_core: ^1.13.1

  #9-Used for accessing Firebase storage and uploading QR Image data
  firebase_storage: ^10.2.9

  #10-Used for building providers
  provider: ^6.0.2

  #11-Sending SMS
  telephony: ^0.1.4

  #12-Used for implementing PDF Invoice
  pdf: ^3.4.2

  #13-Used for printing QR Code in Invoice pdf
  printing: ^5.5.0

  #14-Used for Open File from provided file
  open_file: ^3.2.1

  #15-Used for getting device storage path
  path_provider: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  #Used for App Icon
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/PNG/logo.png"
  adaptive_icon_foreground: "assets/PNG/logo_foreground.png"

flutter:
  uses-material-design: true

  #All assets used in project are defined here
  assets:
    - assets/JPG/
    - assets/SVG/
    - assets/PNG/
    - assets/fonts/
    - assets/images/Baby Shower/
    - assets/images/Cars/
    - assets/images/Home Occasions/
    - assets/images/Others/
    - assets/images/Religious Occasions/
    - assets/images/Wedding/

  #Fonts used in project
  fonts:
     - family: Ubuntu
       fonts:
         - asset: assets/fonts/Ubuntu-Regular.ttf

